### ISSUE TITLE
[TC9.0b15x32, Win7] Installation error

### ISSUE THREAD

**Issue by Helix751** [webmaster442/TCPlayer#1]
Get a "This is not a valid plugin" error msg when trying to install with either automatic or manual TC plugin install function.

![screenshot_1](https://cloud.githubusercontent.com/assets/22524397/18958297/8d781296-8638-11e6-9829-2f48e3f3d4da.png)

**Comment by webmaster442** [comment]
Working on fix. Probably It's because I only exported the Unicode load function, due to a long file name bug I had a while ago. I made some changes, but I need some time for proper testing.

**Comment by Helix751** [comment]
Confirmed it doesn't work on TC8.52a (x32) either.

**Comment by webmaster442** [comment]
Released 1.03 version, that fixes the issue

**Comment by Helix751** [comment]
Same message upon installation under both TCx32 9.0b13 and 8.52a: "This is not a valid plugin!" with version 1.03, 

Can also confirm this only affects TCx32. Under TCx64 plugin installation is Ok.

**Comment by webmaster442** [comment]
Well, actually it seems that I implemented the needed function, but forgot to export it. Uploaded a fixed version, that Works on x86 versions too.  :) Thanks for reporting the issue

**Comment by Helix751** [comment]
Where is the updated version (binaries)? Totalcmd.net doesn´'t have it yet. Sergio Villasecasvillaseca@yahoo.com 

```
El Lunes, 3 de octubre, 2016 15:02:32, Ruzsinszki Gábor <notifications@github.com> escribió:
```

 Well, actually it seems that I implemented the needed function, but forgot to export it. Uploaded a fixed version, that Works on x86 versions too. :) Thanks for reporting the issue—

**Comment by webmaster442** [comment]
Updated binaries were uploaded only to the Github releases page. Updated files are now available on TotalCMD.net also.
