### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by cvelele** [webmaster442/TCPlayer#20]
how to loop song or playlist?

**Comment by webmaster442** [comment]
Currently there's no feature for it, but I will implement it in the next release

**Comment by webmaster442** [comment]
UI for it is implemented, now the backend part remains and after that some testing & releasing a new version. Hopefully I will have time to finish it this week. A new version should be available next week.

**Comment by webmaster442** [comment]
Implemented, will be part of next release build.
