### ISSUE TITLE
Short WAV files playback bug

### ISSUE THREAD

**Issue by ComplexWaveform** [webmaster442/TCPlayer#23]
Hey, thanks for the great plugin! 
However, I have an issue that makes it unusable for me. As a sound designer, I'm always listening through the bunch of short WAV-files using lister. When I'm installing the TCPlayer and trying to open a file, at first Total Commander is trying to open standard lister, and only then it opens TC Player. So, in the beginning, I can hear a short fragment of file playing through the lister at maximum volume, then lister automatically closes, and the file is playing through the TCPlayer. Is it possible to fix this issue?

Thanks!

**Comment by webmaster442** [comment]
Hello. Unfortunately It's a bug of the internal Lister of Total Commander. It takes some time for it to fire plugin code and also It takes time to start the program. As a workaround I would suggest opening the app, and then using the Lister functionality. In this case starting the app doesn't take time, and the files opened with the Lister will be sent to the playlist of the program. Also I created a packer plugin which you can use to send multiple files to the player.
