### ISSUE TITLE
[2.5] "Tag read error" on many MIDI files

### ISSUE THREAD

**Issue by watchmakerful** [webmaster442/TCPlayer#24]
Can't play many MIDI files, it only displays "Tag read error" and does not play. Other files are played correctly. Two sample MIDI files are in the attached ZIP.
[MIDI.ZIP](https://github.com/webmaster442/TCPlayer/files/4365272/MIDI.ZIP)

**Comment by webmaster442** [comment]
For MIDI playback a SoundFont is required, but indeed it wasn't showing the right error message. I flagged this as a bug, Working on it's fix. A note will be added to the readme too.

**Comment by watchmakerful** [comment]
> For MIDI playback a SoundFont is required, but indeed it wasn't showing the right error message. I flagged this as a bug, Working on it's fix. A note will be added to the readme too.

A soundfont is installed correctly, other MIDI files use it, but these ones are not played at all. For example, this file is played fine with the same soundfont. 
[101.zip](https://github.com/webmaster442/TCPlayer/files/4365335/101.zip)

**Comment by webmaster442** [comment]
Fixed in version V2.6
https://github.com/webmaster442/TCPlayer/releases/tag/v.2.6
