### ISSUE TITLE
Output device not saved

### ISSUE THREAD

**Issue by hattesoul** [webmaster442/TCPlayer#3]
Hi,

I use TC (x64) 8.52a with TC Player 1.05.
When I press F3 (view/play) on an MP3 file, TC Player starts normally and plays the file. But I have to change the output device to "Speakers" to hear something. When I close TC Player and play another song, I have to change the output device again to hear it.

**Comment by webmaster442** [comment]
Will look into it.

**Comment by RyanChuang** [comment]
Yes,it did not save the option whatsoever each time launch.

**Comment by webmaster442** [comment]
Initialization now uses the default output device. Once it's changed the player remembers the selected device on next start.
