### ISSUE TITLE
Add to playlist with multi-file selection

### ISSUE THREAD

**Issue by hattesoul** [webmaster442/TCPlayer#4]
Hi,
I use TC (x64) 8.52a with TC Player 1.05 on Windows 10 Pro.
It would be very nice, if TC Player adds automatically all selected files to the playlist, when pressing F3 (view/play), instead of the first selected file only.

**Comment by webmaster442** [comment]
Yes, that would be nice. But there's a catch. Total Commander API only allows the query of the firstly selected file. (Try for example on a buntch of images with the built-in lister) So at the moment it's not possible to implement it :(  For further reference see: http://www.ghisler.ch/board/viewtopic.php?t=6336

**Comment by hattesoul** [comment]
Hi,
maybe I confuse things a bit:
When I select, e.g., 4 JPG files and press F3, the lister window (imagine 1.09) shows me the first selected file, but in the upper right corner there are controls so I can switch to other files. It looks like "<<  1/4  >>", meaning the window displays the 1st of 4 files; and I can switch backward and forward the selected files by clicking "<<" and ">>" respectively.
Or is this a mechanism completely different?
Best regards

**Comment by webmaster442** [comment]
This can only be done with those plugins that draw into the lister window. My plugin starts an external program, then closes the lister window

**Comment by hattesoul** [comment]
Ok, I see.
But is it then possible to "transfer" the list of selected files to the external program, before it closes the lister window? Like writing the list in a temp file, or something similar.

**Comment by webmaster442** [comment]
Implemented using a packer plugin. Select multiple files & with provided packer you can send whole directories to the player :)
