### ISSUE TITLE
Exit on ESC without confirmation

### ISSUE THREAD

**Issue by hattesoul** [webmaster442/TCPlayer#5]
Hi,
I use TC (x64) 8.52a with TC Player 1.05 on Windows 10 Pro.
I would be awesome to have an option to exit TC Player by pressing ESC without a confirmation to really quit the program.

**Comment by webmaster442** [comment]
Will add a setting to disable it.

**Comment by webmaster442** [comment]
Added Settings page, and a setting to disable this behaviour.
