### ISSUE TITLE
Program not reading all the libraries

### ISSUE THREAD

**Issue by c8c8** [webmaster442/TCPlayer#6]
Started using v1.05.  Have confirmed with v1.06 and 8.52a of TC (64-bit).  When starting the program, the message: 

"The program can't start because OptimFROG.dll is missing from your computer. Try reinstalling the program to fix this problem." 

appears and you have to click okay for TC Player to begin.  OptimFROG.dll is in the Engine\x64\ directory.  The only way to resolve the problem is to move OptimFROG.dll from the proper directory in to the main TCPlayerLister\ directory alongside the .exe/wlx files.  

![snap01](https://cloud.githubusercontent.com/assets/23272116/20027352/8dfb83c2-a2d7-11e6-9cda-dab8e156ccb0.png)

**Comment by webmaster442** [comment]
Found the problem, Windows 10 doesn't display an error on dll load. Fixed the loading issue, but the Bass OptimFrog plugin is broken at the moment. It doesn't play back any OFR files, so the simplest solution is to remove the broken feature & when it's fixed re enable the support for it.
