### ISSUE TITLE
Dosen't play MIDI [fixed in 1.07]

### ISSUE THREAD

**Issue by c8c8** [webmaster442/TCPlayer#7]
Using v1.06 and TC 8.52a (64 bit) on Win7-64. 

Trying to play any *.mid file doesn't work.  Only renders the error message: 

"Load failed
Bass error code: 41
Error Description: FileFormat"

I have confirmed that my test MIDI files play in all of my other MIDI players.  They are basic format-1.  I have set my MIDI soundfont in the settings section (using 32MbGMStereo.sf2). 

![snap02](https://cloud.githubusercontent.com/assets/23272116/20027385/bdcf7f3a-a2d8-11e6-92eb-7275e1384e7b.png)

**Comment by webmaster442** [comment]
Well, shit :D I accidently copied the x86 version of the bassmidi.dll to the x64 folder, so loading it fails. Fixed the error, will release a fixed version soon.

**Comment by c8c8** [comment]
Thanks for the super-fast turnaround.  The errors are gone and 1.07 now shows as playing, but it produces no sound (exclusively on midi files).  Tried using the Ct8mgm.sf2 soundfont with the same result.
