### ISSUE TITLE
default play back device can't be saved

### ISSUE THREAD

**Issue by lczlcz** [webmaster442/TCPlayer#9]
I have speakers and headset enabled.  Somehow when I play a song, the default play back device is the headset and not the speaker even the speaker is the default play back device under win10.  When I select the play back device in TC player, it works for the next song.  Somehow when I close TC player and open it again for another song, the default play back device becomes headset again.

**Comment by webmaster442** [comment]
Are you using the latest version? It had a similar issue (https://github.com/webmaster442/TCPlayer/issues/3), but it was fixed in version 1.06

**Comment by lczlcz** [comment]
Ah, I apologize for the inconvenience.
I downloaded your program from totalcmd.net, which is actually version 1.05 and didn't look what you have here.  Now I downloaded version 2.0 with no problem at all. 
Thank you very much for the great work.
